name: Android CI

on:
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a release with ZIP asset?'
        required: false
        default: 'false'
        type: choice
        options:
          - 'false'
          - 'true'
  push:
    branches: test
  pull_request:
    branches: test

jobs:
  build:
    runs-on: macos-26
    permissions:
      contents: write

    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Upload CI module zip as artifact zip
        uses: actions/upload-artifact@v4
        with:
          name: spoofVendingSdktoggle_#${{ github.run_number }}
          path: '*'

      - name: Create release ZIP
        if: ${{ github.event.inputs.create_release == 'true' }}
        run: zip -r release.zip *

      - name: Create or Upload Release
        if: ${{ github.event.inputs.create_release == 'true' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "CI Release #${{ github.run_number }}"
          files: release.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ github.token }}
